syntax = "proto3";

package grpc_astra;
import "google/protobuf/wrappers.proto";
import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";
import "units.proto";

//Define the Astra service
service Astra {
    rpc Search (SearchRequest) returns (SearchResponse) {}
}

message SearchRequest {
    TypeExpression types = 1;// SLLTypes to search
    SearchClause search_clause = 2; // The filter conditions that the returned objects must meet
    bool exclude_developer_objects = 3;
    google.protobuf.UInt32Value max_items = 4;
}

message TypeExpression {
    oneof type_expression {
        TypeFilter single_type = 1; // Single type filter
        LogicalExpression logical = 2; // Logical expression to combine multiple types
    }

    message TypeFilter {
        string type = 1;       // Type ("Object" or "Model")
        repeated SubtypeExpression subtypes = 2;    // List of subtypes
    }
    // Logical operation for combining type expressions
    message LogicalExpression {
        LogicalOperator operator = 1; // AND, OR, EXCEPT
        repeated TypeExpression expressions = 2; // sub-expressions
    }
}

message SubtypeExpression {
    oneof subtype_expression {
        string subtype = 1; // A single subtype filter
        LogicalExpression logical = 2; // A logical expression to combine multiple subtypes
    }

    message LogicalExpression {
        LogicalOperator operator = 1; // AND, OR, EXCEPT
        repeated SubtypeExpression expressions = 2; // sub-expressions
    }
}

enum LogicalOperator {
    OR = 0;          // OR operation
    EXCEPT = 1;      // EXCEPT (set difference) operation -- Except is essentially ButNot, i.e "We want this type but not that type"
}

// Filter clauses
message SearchClause {
    oneof clause {
        // Trivially true clause
        google.protobuf.Empty true_clause = 1;

        // Trivially false clause
        google.protobuf.Empty false_clause = 2;

        // Negation of the enclosed clause
        NotClause not_clause = 3;

        // Conjunction (AND)
        AndClause and_clause = 4;

        // Disjunction (OR)
        OrClause or_clause = 5;

        // Single predicate
        Predicate simple = 6;
    }

    // Negation
    message NotClause {
        SearchClause clause = 1;
    }

    // Conjunction (AND)
    message AndClause {
        repeated SearchClause clauses = 1;
    }

    // Disjunction (OR)
    message OrClause {
        repeated SearchClause clauses = 1;
    }

    // Predicate consisting of a function and its arguments
    message Predicate {
        PredicateArgument lhs = 1;
        PredicateArgument rhs = 2;
        Operator op = 3;      // Comparison operator
         
        message PredicateArgument {
            oneof argument {
                FieldPath field = 1; // Field name (e.g., "DeveloperObject")
                Function function = 2; // Function to apply (e.g., "Length")
                Value value = 3; // Value to compare against
            }
        }

        message FieldPath {
            repeated Segment segments = 1;

            message Segment {
                string name = 1;
                Index indices = 2;
            }

            message Index {
                oneof spec {
                    PartSpec one = 1;  // Multiple OR an indexed composite
                    TwoPartSpec two = 2;  // Multiple and indexed composite
                }
            }

            message PartSpec {
                oneof part {
                    All all = 1; // All entries in a Multiple field.
                    int32 idx = 2; // A single element of a Multiple field
                    Range range = 3; // A range of elements in a Multiple field.
                }

                message All{}
            }

            message TwoPartSpec {
                PartSpec part = 1;
                int32 idx = 2;
            }
        }

        message Function {
            FunctionOptions function = 1; // Function to apply (e.g., "Length")
            PredicateArgument arg = 2; // Argument to the function

            enum FunctionOptions {
                LENGTH = 0;
            }
        }
        
        // Comparison operators
        enum Operator {
            EQUAL = 0;
            NOT_EQUAL = 1;
            GREATER_THAN = 2;
            LESS_THAN = 3;
            GREATER_THAN_OR_EQUAL = 4;
            LESS_THAN_OR_EQUAL = 5;
            IN = 6;
            NOT_IN = 7;
        }
    }
}

// Represents a value in a predicate
message Value {
    oneof val {
        PrimValue single = 1; // Single value
        PrimList multiple = 2; // Multiple values
        TypeExpression object = 3; // Object value
    }
}

message PrimValue {
    oneof prim {
        string string = 1; // String representation
        bool bool = 2;     // Boolean representation
        int64 int = 3;     // Integer representation
        double float = 4;  // Float representation
        string variant = 5;      // Variant of an SLL Enum (for Expression fields)
        google.protobuf.Timestamp date = 6; // Date representation
        Quantity quantity = 7; // Quantity representation
        string raw_string = 8; // raw string representation (for raw string values from JSON)
    }
}

message PrimList {
    repeated PrimValue values = 1;
}

message Quantity {
    double value = 1;
    units.UnitExpr units = 2; // Units defined in units.proto
}


message Range {
    int32 start = 1;
    int32 end = 2;
}

// Response message for Search RPC
message SearchResponse {
    repeated SearchResult results = 1;    // List of search results
    uint32 total_count = 2;              // Total number of results (useful for pagination)
}

// Individual search result
message SearchResult {
    string id = 1;                       // Unique identifier of the found object
    string type = 2;                     // Type of the object
}